require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
require "user.cmp"
require "user.telescope"
-- require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"   -- status line
require "user.toggleterm"
require "user.project"
require "user.illuminate" -- highlight other uses of the word under cursor
require "user.indentline" -- show vertical indent lines
require "user.alpha"
require "user.lsp"
-- require "user.dap"
require "user.motion"
